### PR TITLE
added dist folder and output of build to repo

### PR DESCRIPTION
**Pull request by mackenza**
as per #124 the cdns want minified files and it also makes reference to having issues with mixed case.

I modified the grunt build task to change the case to all lowercase. The localize was also failing because of an incorrect src name for the map file. This may have been introduced when the deps were updated. Fixed now.

I also removed the dist folder from the .gitignore.

### CODE REVIEW

**Comment by softwarespot** [comment]
Maybe bower's main file should be changed as well. I am not really understanding the name change though.

**Comment by ionutvmi** [comment]
Thank you for this !

**Comment by mackenza** [comment]
@softwarespot I was merely going by what #124 said as he seemed to have some insight into cdn best practices. I have no issues leacing the name as is if that's what is decided

**Comment by softwarespot** [comment]
I am just curious how it affects those who rely on the name being the previous one. I am always happy moving forward than backwards!

**Comment by mackenza** [comment]
I didn't change the name of the source file, only the built one that ends up in /dist so it should be easy to absorb. I suppose we could have both mixed and lowercase versions in /dist and only make the lower case known to whatever CDNs are made aware of the library?

**Comment by ionutvmi** [comment]
From my point of view the way we have it in this PR is ok.
The original file was not affected and a copy is created in the dist/ folder that will be used specifically for the CDN.

**Pull request merged**
