### PR TITLE
align more closely with airbnb rules

### PR DESCRIPTION
**Pull request by mackenza**
@jehna did a great job with the eslint grunt task. I just made some small changes to `.eslintrc` to not ignore certain rules and modify others. If the code is going to adhere to a standard (and the airbnb one is good) then why not align as closely as possible?

The `markers` override is for the `!` in the opening comment and the `\` which makes up the `\\\` comments, which I assume is for generating docs (although unused, I think).

### CODE REVIEW

**Comment by softwarespot** [comment]
Hi, thanks for your kind words, as I implemented the grunt task =). As for your recommendations, I kind of purposely left vars-on-top for ease of moving to ES2015 in the future, but agree that it doesn't conform to the exact standard set out by AIrbnb. So there was method to my madness!

**Comment by mackenza** [comment]
Oh, I guess I read the pr wrong, sorry. 

If es6 is in the picture, I kind of think it should be written in es6 and babelled. If that happens then make them lets in the loops.

**Comment by softwarespot** [comment]
I honestly would like this to move to ES2015 too. Anyhow, good PR.

**Comment by ionutvmi** [comment]
Please fix the conflicts.

**Comment by mackenza** [comment]
done. the merge of #112 made my earlier clean commit break ;)

**Comment by softwarespot** [comment]
Sorry about that :-1:

**Comment by mackenza** [comment]
it's all good :dancers:

**Pull request merged**
